Ilcm
GovTechSG/stackops-docs pull request #88
Opened 2023-07-12 07:48 UTC by SenthilKumarSivakami

2023-07-12 10:17 UTC, o20ne requested changes

2023-07-12 10:17 UTC, o20ne commented on faqs.md
> +- (Upcoming) Designed for collaboration across projects within StackOps
Let's remove "Designed for"
- (Upcoming) Collaboration across projects within StackOps
would be better

2023-07-12 10:17 UTC, o20ne commented on faqs.md
> +- Enhanced Elastic Common Schema to improve Data identity, Data profiling and Data MarketPlace
- Enhanced Elastic Common Schema to improve Data identity, Data profiling and enables Data MarketPlace

2023-07-12 10:17 UTC, o20ne commented on faqs.md
> +- We constantly strive to stay up to date with the evolution of technology, including advancements related to competency frameworks such as OpenTelemetry.
Let's remove "related to competency frameworks"

2023-07-12 13:14 UTC, SenthilKumarSivakami commented on faqs.md
> +- (Upcoming) Designed for collaboration across projects within StackOps
done

2023-07-12 13:16 UTC, SenthilKumarSivakami commented on faqs.md
> +- Enhanced Elastic Common Schema to improve Data identity, Data profiling and Data MarketPlace
Does improving Data Identity and Data profiling enable Data Marketplace?

2023-07-12 13:22 UTC, SenthilKumarSivakami commented on faqs.md
> +- Enhanced Elastic Common Schema to improve Data identity, Data profiling and Data MarketPlace
done

2023-07-12 13:27 UTC, SenthilKumarSivakami commented on faqs.md
> +- We constantly strive to stay up to date with the evolution of technology, including advancements related to competency frameworks such as OpenTelemetry.
done, this info was duplicated in 2 places so have removed the redundant instance. Thanks!

2023-07-13 01:35 UTC, paulkarippa approved these changes

2023-07-13 01:56 UTC, o20ne approved these changes

2023-07-13 02:32 UTC, merged